site_name: Edgar Ramírez DocOps Exercise
site_description: This is an exercise of a static website using the DocOps resources.
site_author: Edgar Ramírez

nav:
  - My Profile: index.md
  - Education: education.md
  - Work Experience: work-experience.md
  - Skills: skills.md
  - Selected Past Work: selected-past-work.md

markdown_extensions:
  - attr_list

theme:
  name: material
  logo: images/wizeline_isotype.png
  features:
    - toc.integrate

plugins:
  - search

extra_css:
    - css/extra.css